version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: nuget restore
build:
  project: Codex.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: bin\**\*
  name: Installer